version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\WebApp\GamesStore_11883_Client
  
hooks:
  BeforeInstall:
    - location: .\StageArtifact.ps1
    - location: .\CreateWebSite.ps1