version: 0.0
os: windows
files:
  - source: \GamesStore_11883_Client\*.*
    destination: c:\inetpub\wwwroot\GamesStore_11883_Client
hooks:
  BeforeInstall:
    - location: \deletewebsite.ps1
      timeout: 180
  AfterInstall:
    - location: \installwebsite.ps1
      timeout: 180
